//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryGenerator.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalleryGenerator.Resources.Translations.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Generator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close without saving changes?.
        /// </summary>
        public static string CloseWithoutSavingChanges {
            get {
                return ResourceManager.GetString("CloseWithoutSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure You want to stop? Work can&apos;t be resumed..
        /// </summary>
        public static string ConfirmBreakWorker {
            get {
                return ResourceManager.GetString("ConfirmBreakWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy original files to gallery.
        /// </summary>
        public static string CopyOriginalFiles {
            get {
                return ResourceManager.GetString("CopyOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate work time.
        /// </summary>
        public static string EstimateWorkTime {
            get {
                return ResourceManager.GetString("EstimateWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating work time....
        /// </summary>
        public static string EstimatingWorkTime {
            get {
                return ResourceManager.GetString("EstimatingWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed directories.
        /// </summary>
        public static string FailedDirectories {
            get {
                return ResourceManager.GetString("FailedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed files.
        /// </summary>
        public static string FailedFiles {
            get {
                return ResourceManager.GetString("FailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions.
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill all fields..
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery name.
        /// </summary>
        public static string GalleryName {
            get {
                return ResourceManager.GetString("GalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory.
        /// </summary>
        public static string InputDir {
            get {
                return ResourceManager.GetString("InputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input validation.
        /// </summary>
        public static string InputValidation {
            get {
                return ResourceManager.GetString("InputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium images height.
        /// </summary>
        public static string MediumImgHeight {
            get {
                return ResourceManager.GetString("MediumImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium images width.
        /// </summary>
        public static string MediumImgWidth {
            get {
                return ResourceManager.GetString("MediumImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open gallery after completed..
        /// </summary>
        public static string OpenAfterFinish {
            get {
                return ResourceManager.GetString("OpenAfterFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other files.
        /// </summary>
        public static string OtherFiles {
            get {
                return ResourceManager.GetString("OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        public static string OutputDir {
            get {
                return ResourceManager.GetString("OutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve medium images aspect ratio.
        /// </summary>
        public static string PreserveAspectRatio {
            get {
                return ResourceManager.GetString("PreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} has ocurred! Generating Gallery failed..
        /// </summary>
        public static string ProcessInterruptedByError {
            get {
                return ResourceManager.GetString("ProcessInterruptedByError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changes.
        /// </summary>
        public static string SettingsChanges {
            get {
                return ResourceManager.GetString("SettingsChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped extensions.
        /// </summary>
        public static string SkippedExtensions {
            get {
                return ResourceManager.GetString("SkippedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop work.
        /// </summary>
        public static string StopWork {
            get {
                return ResourceManager.GetString("StopWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery summary.
        /// </summary>
        public static string SummaryWindow {
            get {
                return ResourceManager.GetString("SummaryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails height.
        /// </summary>
        public static string ThumbImgHeight {
            get {
                return ResourceManager.GetString("ThumbImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails width.
        /// </summary>
        public static string ThumbImgWidth {
            get {
                return ResourceManager.GetString("ThumbImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbs grid size.
        /// </summary>
        public static string ThumbsGridSize {
            get {
                return ResourceManager.GetString("ThumbsGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process cancelled..
        /// </summary>
        public static string WorkCancelled {
            get {
                return ResourceManager.GetString("WorkCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        public static string WorkCompleted {
            get {
                return ResourceManager.GetString("WorkCompleted", resourceCulture);
            }
        }
    }
}
