//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryGenerator.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalleryGenerator.Resources.Translations.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Generator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy original files to gallery.
        /// </summary>
        public static string CopyOriginalFiles {
            get {
                return ResourceManager.GetString("CopyOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating work time....
        /// </summary>
        public static string EstimatingWorkTime {
            get {
                return ResourceManager.GetString("EstimatingWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery name.
        /// </summary>
        public static string GalleryName {
            get {
                return ResourceManager.GetString("GalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory.
        /// </summary>
        public static string InputDir {
            get {
                return ResourceManager.GetString("InputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium images height.
        /// </summary>
        public static string MediumImgHeight {
            get {
                return ResourceManager.GetString("MediumImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium images width.
        /// </summary>
        public static string MediumImgWidth {
            get {
                return ResourceManager.GetString("MediumImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        public static string OutputDir {
            get {
                return ResourceManager.GetString("OutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve medium images aspect ratio.
        /// </summary>
        public static string PreserveAspectRatio {
            get {
                return ResourceManager.GetString("PreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} has ocurred! Please check log for details..
        /// </summary>
        public static string ProcessInterruptedByError {
            get {
                return ResourceManager.GetString("ProcessInterruptedByError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails height.
        /// </summary>
        public static string ThumbImgHeight {
            get {
                return ResourceManager.GetString("ThumbImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails width.
        /// </summary>
        public static string ThumbImgWidth {
            get {
                return ResourceManager.GetString("ThumbImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process cancelled..
        /// </summary>
        public static string WorkCancelled {
            get {
                return ResourceManager.GetString("WorkCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        public static string WorkCompleted {
            get {
                return ResourceManager.GetString("WorkCompleted", resourceCulture);
            }
        }
    }
}
